
# Site settings
title: 'First 100 for #NoDAPL'
email: dhornbein@gmail.com
description: 'Retail and Service Industries global fundraising campaign for Standing Rock'
baseurl:          
url:              http://first100network.com
name:             'First 100 for #NoDAPL'
permalink:        pretty
twitter_username: hornbein
github_username:  dhornbein
port: 4040

# Build settings
markdown: kramdown
exclude:  [node_modules]

# Resources
forms:
 join: https://goo.gl/forms/ySeowrZ7zSHKVqfp2
 report: https://goo.gl/forms/zkztUhk8AS42VRhX2
prints:
 pos: https://drive.google.com/open?id=0BweC4_lD2gMbZ013TUZIX09PdDg
gofundme: https://www.gofundme.com/3s-stand-with-standing-rock
fbgroup: https://www.facebook.com/groups/1131815053563674

# Payment
address: 26 Glendale Ave Asheville NC 28803
sponsor: Community Roots